version: '3'
networks:
  stack: {}
volumes:
  postgres-data: {}
services:
  postgres:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: todolist
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d pocketlaw -U postgres']
      interval: 5s
      timeout: 5s
      retries: 6
    networks:
      - stack
    volumes:
      - postgres-data:/var/lib/postgresql/data
